### ISSUE TITLE
google popup not coming after logout.

### ISSUE THREAD

**Issue by pradeekumar** [heresy/angular2-social-login#36] opened 2018-06-14 06:28 UTC
Only first-time Gmail popup comes. after logging out second-time when I trying to logging popup doesn't come and it logging with the previous account.

**I want to logging with different Gmail account each time I logged out**

**Comment by achus-ui** [comment] 2018-07-11 06:06
I do have the same issue, somebody please respond to this issue!

**Comment by achus-ui** [comment] 2018-07-11 07:53
@pradeekumar bro I figured out the issue and resolved it! 
Root Cause: At the time of login certain key-values is being added as cookies, this cookies will decided which user will go as a login user. Unfortunately in this package they are not clearing cookies, so as u said, you login for the first time and then logout. Again u r trying to login and it will take you to the first user automatically and not allowing you to choose another account. This can be fixed by clearing the cookies added while logging in. You can  clear the cookies from your application at the time of logout event trigger. Hope you got my point

**Comment by pradeekumar** [comment] 2018-07-13 07:33
@achus-ui thanks for the help, but I changed my login plugin.

**Comment by achus-ui** [comment] 2018-07-13 08:10
Bro now which plugin you are using?

**Comment by achus-ui** [comment] 2018-07-13 08:11
Bro now which plugin you are using!


*Regards*
*Harikrishnan S*
*Mob: +91 9847 400 944*

**Comment by pradeekumar** [comment] 2018-07-16 05:11
Hi @achus-ui   
I am using this plugin.
https://github.com/abacritt/angularx-social-login

**Comment by achus-ui** [comment] 2018-07-16 07:04
Thanks!

*Regards*
*Harikrishnan S*
*Mob: +91 9847 400 944*

**Closed as completed** 2021-12-19 10:45 UTC
